accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('logout/', views.sign_out, name='logout'),
    path('details/', views.details, name='details'),
]

again/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('finances/', include('finances.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

finances/urls.py
from django.urls import path

from . import views

app_name = 'finances'

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.list_transactions, name='list'),
    path('add_transaction/', views.add_transaction, name='addtr'),
    path('add_account/', views.add_account, name='addac'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('transfer/', views.transfer, name='transfer'),
]

fkeeper/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('finances/', include('finances.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

fkeeper/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader

# Create your views here.
def index(request):
    # Uncomment following 2 lines for automatic redirects
    # from index page to dashboard for authorized users (for Kirill)
    # if request.user.is_authenticated:	# TODO: replace with something more beautiful
    #     return HttpResponseRedirect('/finances/dashboard')
    template = loader.get_template('fkeeper/index.html')
    return HttpResponse(template.render({}, request))

fkeeper/templates/fkeeper/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Finance Keeper{% endblock %}</title>
    <link type="text/css" rel="stylesheet" href="{% static "base/base.css" %}">
    <script type="text/javascript" src="{% static 'base/base.js' %}"></script>
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

fkeeper/templates/fkeeper/index.html
{% extends 'fkeeper/base.html' %}
{% load static %}
{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static "finances/index.css" %}">
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
    <h1>Finance Keeper</h1>
        <p>
            Wercome here, {{ user }}!
        </p>

        {% if user.is_staff %}
            <p>
                Visual editing is accessible through
                <a href="admin/">admin panel</a>.
            </p>
        {% endif %}

        <div class="tech-info">
            <h3>
                Technical information.
            </h3>
            <p>Current user is <a href="{% url 'accounts:details' %}">{{ user }}</a></p>
            <p>Press
                <a href="{% url 'accounts:logout' %}">here</a>
                to log out.
            </p>

            <h3>Useful links</h3>
            <ul>
                <li><a href="{% url 'finances:dashboard' %}">Personal dashboard</a></li>
                <li><a href="{% url 'finances:list' %}">List of all completed transactions</a></li>
                <li><a href="{% url 'finances:addtr' %}">Add new transaction</a></li>
                <li><a href="{% url 'finances:addac' %}">Add new account</a></li>
            </ul>
        </div>


    {% else %}
        <div class="split split_left">
            <div class = "authors">
                <p>Made by:</p>
                <p><a href="https://github.com/Kickoman">Kanstancin Novikau</a></p>
                <p><a href="https://github.com/LizaTheGreatest">Liza Phan</a></p>

            </div>
            <div class="header">
                <p>Finance Keeper</p>
            </div>
                

        </div>

        <div class="split split_right bg_primary">
            <section class = "auth">
                <form method="post" action="{% url 'accounts:sign_in' %}">
                    {% csrf_token %}
                    <input id="usrn" type="text" name="username" placeholder="USERNAME">
                    <br>
                    <br>

                    <input id="pw" type="password" name="password" placeholder="PASSWORD">
                    <br>
                    <br>
                    <!-- <input id="sb" type="submit" value="Sign in"> -->
                    <button type="submit">Sign in</button>
                </form>

                <p>Create an account <a href="{% url 'accounts:sign_up' %}">Sign up</a></p>

                    
            </section>
        

    {% endif %}
{% endblock %}